// <auto-generated />
using System;
using Ecommerce.Micro.CarShop.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Micro.CarShop.Migrations
{
    [DbContext(typeof(ContextCarShop))]
    partial class ContextCarShopModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ecommerce.Micro.CarShop.Models.CarShopSession", b =>
                {
                    b.Property<int>("CarShopSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CarShopSessionId");

                    b.ToTable("CarShopSession");
                });

            modelBuilder.Entity("Ecommerce.Micro.CarShop.Models.CarShopSessionDetail", b =>
                {
                    b.Property<int>("CarShopSessionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarShopSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductSelected")
                        .HasColumnType("text");

                    b.HasKey("CarShopSessionDetailId");

                    b.HasIndex("CarShopSessionId");

                    b.ToTable("CarShopSessionDetail");
                });

            modelBuilder.Entity("Ecommerce.Micro.CarShop.Models.CarShopSessionDetail", b =>
                {
                    b.HasOne("Ecommerce.Micro.CarShop.Models.CarShopSession", "CarShopSession")
                        .WithMany("ListDetail")
                        .HasForeignKey("CarShopSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
